services:
  madro_db:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_DB: madro
      POSTGRES_USER: madro
      POSTGRES_PASSWORD: madro
    ports:
      - "5432:5432"
    volumes:
      - pgdata_madro:/var/lib/postgresql/data

  dowser_db:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_DB: dowser
      POSTGRES_USER: dowser
      POSTGRES_PASSWORD: dowser
    ports:
      - "5433:5432"
    volumes:
      #- ./dowser-dump.sql:/tmp/dowser-dump.sql
      - pgdata_dowser:/var/lib/postgresql/data

volumes:
  pgdata_madro:
  pgdata_dowser:
